### ISSUE TITLE
bag.h not found

### ISSUE THREAD

**Issue by shujaatak** [rolker/bagViewer#1]
Can you please include that library source in this repository? It would be awesome to have everything in one place. It would also be awesome if building the bagViewer also builds the required libraries and automatically link them. It would then be a nice one place solution reducing the hassle.

**Comment by rolker** [comment]
The bagViewer used to be part of the Open Navigation Surface's bag library, but it was decided to split them up to keep the bag library light weight.

By cloning and building the following, you'll get bag.h.

https://github.com/OpenNavigationSurface/BAG
